#!/bin/sh
#
# @name AMOVLAB SU17
#
# @type Quadrotor x
# @class Copter
#
# @maintainer Amovlab Lv Guofei <service@amovauto.com>
#
#

. ${R}etc/init.d/rc.mc_defaults

param set-default MPC_XY_P 0.70
param set-default MPC_XY_VEL_P_ACC 2.20
param set-default MPC_XY_VEL_D_ACC 0.35

param set-default MC_ROLLRATE_P 0.120
param set-default MC_PITCHRATE_P 0.18
param set-default MC_ROLLRATE_I 0.115
param set-default MC_PITCHRATE_I 0.025
param set-default MC_ROLLRATE_D 0.025
param set-default MC_PITCHRATE_D 0.0030

# Square quadrotor X PX4 numbering
param set-default CA_ROTOR_COUNT 4
param set-default CA_ROTOR0_PX 0.10
param set-default CA_ROTOR0_PY 0.13
param set-default CA_ROTOR1_PX -0.10
param set-default CA_ROTOR1_PY -0.13
param set-default CA_ROTOR2_PX 0.10
param set-default CA_ROTOR2_PY -0.13
param set-default CA_ROTOR2_KM -0.05
param set-default CA_ROTOR3_PX -0.10
param set-default CA_ROTOR3_PY 0.13
param set-default CA_ROTOR3_KM -0.05
